#!/bin/bash
#vim: ft=sh,tw=0

set -e

plugged=''
battery_low=''
battery_quarter=''
battery_half=''
battery_three_quarters=''
battery_full=''

critical=10
quarter=25
half=50
three_quarters=75
full=90

data=$(acpi | awk '{gsub(/,|\%/,""); print $3,$4,$5}')
read stats level remaining <<< $data

icon=''
if [ $stats != "Discharging" ]; then
  icon="$plugged "
fi
if [ $level -lt $critical ]; then
  icon=$icon$battery_low
elif [ $level -lt $quarter ]; then
  icon=$icon$battery_quarter
elif [ $level -lt $half ]; then
  icon=$icon$battery_half
elif [ $level -lt $three_quarters ]; then
  icon=$icon$battery_three_quarters
elif [ $level -gt $full ]; then
  icon=$icon$battery_full
fi

out=$icon$level\%

# Check if unset
# https://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash#13864829
if [ -z ${remaining+x} ]; then
  out="$out ($remaining)"
fi
echo $out
